dist: xenial
language: python
sudo: false
cache: pip

python:
  - "3.5"

branches:
  only:
    - master

env:
  - DJANGO="django>=2.1,<2.3"
  - DJANGO="django>=1.11,<1.12"

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - ./runflake8
  - ./runisort
  - npm install jslint -g
  - jslint django_netjsongraph/static/netjsongraph/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - coverage run --source=django_netjsongraph runtests.py
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4 ]]; then ./tests/manage.py makemigrations django_netjsongraph --dry-run | grep "No changes detected"; fi

after_success:
  coveralls
